### ISSUE TITLE
Add add looting plz u say 20 stars

### ISSUE THREAD

**Issue by UniversaMp** [Volcano-MP/Volcano-8.51#11]
Add add looting plz u say ,20 stars

**Comment by dor1q** [comment]
no

**Comment by UniversaMp** [comment]
> no

Lit u don't uknow Code

**Comment by dor1q** [comment]
lit u use this gs for ur shit discord server with same name lmaooo

**Comment by UniversaMp** [comment]
> lit u use this gs for ur shit discord server with same name lmaooo

I am not the owner L

**Comment by Jyzodev** [comment]
kys
